/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4-dev at Wed Sep 16 10:37:31 2015. */

#include "rpcproto.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MethodInfo_fields[6] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, MethodInfo, name, name, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MethodInfo, min_args, name, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, MethodInfo, max_args, min_args, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, MethodInfo, description, max_args, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, MethodInfo, arg_info, description, 0),
    PB_LAST_FIELD
};

const pb_field_t RPCMessage_fields[7] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, RPCMessage, type, type, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, RPCMessage, method, type, &MethodInfo_fields),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, RPCMessage, name, method, 0),
    PB_FIELD(  4, UINT32  , REPEATED, CALLBACK, OTHER, RPCMessage, args, name, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, RPCMessage, result, args, 0),
    PB_FIELD(  7, ENUM    , OPTIONAL, STATIC  , OTHER, RPCMessage, error, result, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RPCMessage, method) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MethodInfo_RPCMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RPCMessage, method) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MethodInfo_RPCMessage)
#endif


